# Generated by Django 5.2.2 on 2025-11-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarga',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='descargas/'),
        ),
    ]
