# Generated by Django 5.2.2 on 2025-11-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_descarga_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarga',
            name='idioma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
