# Generated by Django 5.2.2 on 2025-11-13 23:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_descarga_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarga',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
