# Generated by Django 5.2.2 on 2025-11-20 16:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarga',
            name='requisitos',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
