# Generated by Django 5.2.2 on 2025-11-20 16:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_descarga_requisitos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descarga',
            old_name='requisitos',
            new_name='requisitosmax',
        ),
        migrations.AddField(
            model_name='descarga',
            name='requisitosmin',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
